version: '4.1'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=OgenBertrand
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres-db-network
    restart: unless-stopped
volumes:
  postgres-db-volume:
networks:
  postgres-db-network:
    driver: bridge