#spring:
 # application:
  #  name: e2e-game-app
  #profile:
   # active: dev,postgres

#management:
 # endpoints:
  #  web:
   #   exposure:
    #    include: health, metrics
  #endpoint:
   # health:
    #  show-details: always